services:
  core:
    build:
      context: ..
      dockerfile: core/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    env_file:
      - ../../config/core-config-envs
    logging:
      driver: "json-file"
    restart: on-failure
    depends_on:
      glowroot-central:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:management
    env_file:
      - ../../config/rabbitmq-config-envs
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_ADMIN_PORT}:15672"
    restart: on-failure
    healthcheck:
      # rabbitmq server crashes if any rabbitmq-diagnostics cmd is run very soon
      # after starting, so can't check too aggressively here
      test: rabbitmq-diagnostics -q check_running
      interval: 30s
      timeout: 10s
      retries: 3
  cassandra:
    image: cassandra
    restart: on-failure
    environment:
      # if set too high the process will get OOM killed. Need to make configurable.
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=250M
  glowroot-central:
    build:
      context: ..
      dockerfile: core/Dockerfile.glowroot-central
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    env_file:
      - ../../config/glowroot-config-envs
    ports:
      - "${GLOWROOT_ADMIN_PORT}:4000"
    restart: on-failure
    depends_on:
       - cassandra

