FROM glowroot/glowroot-central

ARG DOMAIN
RUN openssl req -new -x509 -nodes -days 365 -out ui-cert.pem -keyout ui-key.pem -subj "/C=GB/ST=London/L=London/O=UCLH/OU=CRIU/CN=${DOMAIN}"

RUN sed -i "s/^ui.https=.*$/ui.https=true/" glowroot-central.properties

