services:
  hl7-reader:
    build:
      context: ..
      dockerfile: hl7-reader/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    env_file:
      - ../../config/hl7-reader-config-envs
    logging:
      driver: "json-file"
    restart: "no"
    depends_on:
      # Uses services from core, orchestrate using the EMAP setup package
      - glowroot-central
      - rabbitmq
    ports:
      - "${HL7_READER_PORT}:8080"
